import * as BugList from "buglist";
import * as Global from "global";

export function init($container, usesComponents) {
    const releases = Global.releaseData();

    BugList.append({
        id: "beta-open-blockers",
        $container: $container,
        title: `${releases.beta.version} (Beta) Functional Open Blockers`,
        description: "TODO",
        query: {
            resolution: "---",
            f1: "cf_status_firefox_beta",
            o1: "equals",
            v1: "affected",
            f2: "cf_tracking_firefox_beta",
            o2: "equals",
            v2: "blocking",
        },
        usesComponents: usesComponents,
    });

    BugList.append({
        id: "beta-unfixed-new-regressions",
        $container: $container,
        title: `${releases.beta.version} (Beta) Unfixed New Regressions`,
        description: "TODO",
        query: {
            resolution: ["FIXED", "---"],
            keywords: "regression",
            keywords_type: "allwords",
            f1: "cf_status_firefox_beta",
            o1: "anyexact",
            v1: "affected, fix-optional, wontfix",
            f2: "cf_status_firefox_release",
            o2: "anyexact",
            v2: "disabled, unaffected, ---",
            f3: "reporter",
            o3: "notsubstring",
            v3: "intermittent-bug-filer@mozilla.bugs",
        },
        usesComponents: usesComponents,
    });

    BugList.append({
        id: "beta-open-carryover-regressions",
        $container: $container,
        title: `${releases.beta.version} (Beta) Open Carryover Regressions`,
        description: "TODO",
        query: {
            keywords: "regression,",
            keywords_type: "allwords",
            f1: "cf_status_firefox_beta",
            o1: "equals",
            v1: "affected",
            f2: "OP",
            j2: "OR",
            f3: "cf_status_firefox_release",
            o3: "equals",
            v3: "affected",
            f4: "cf_status_firefox_release",
            o4: "equals",
            v4: "fix-optional",
            f5: "cf_status_firefox_release",
            o5: "equals",
            v5: "wontfix",
            f6: "CP",
            f7: "reporter",
            o7: "notsubstring",
            v7: "intermittent-bug-filer@mozilla.bugs",
        },
        usesComponents: usesComponents,
    });

    BugList.append({
        id: "beta-severe-carryover-regressions",
        $container: $container,
        title: `${releases.beta.version} (Beta) Severe Carryover Regressions`,
        description: "TODO",
        query: {
            bug_severity: ["blocker", "S1", "critical", "S2", "major"],
            keywords: "regression",
            keywords_type: "allwords",
            f1: "cf_status_firefox_beta",
            o1: "equals",
            v1: "affected",
            f2: "OP",
            j2: "OR",
            f3: "cf_status_firefox_release",
            o3: "equals",
            v3: "affected",
            f4: "cf_status_firefox_release",
            o4: "equals",
            v4: "fix-optional",
            f5: "cf_status_firefox_release",
            o5: "equals",
            v5: "wontfix",
            f6: "CP",
        },
        usesComponents: usesComponents,
    });

    BugList.append({
        id: "beta-new-top-crashers",
        $container: $container,
        title: `${releases.beta.version} (Beta) New Top Crashers`,
        description: "TODO",
        query: {
            resolution: "---",
            keywords: "crash, topcrash",
            keywords_type: "anywords",
            f1: "cf_status_firefox_beta",
            o1: "equals",
            v1: "affected",
            f2: "cf_tracking_firefox_beta",
            o2: "anyexact",
            v2: "+,blocking",
        },
        usesComponents: usesComponents,
    });

    BugList.append({
        id: "beta-tracked-crashers",
        $container: $container,
        title: `${releases.beta.version} (Beta) Tracked Crashers`,
        description: "TODO",
        query: {
            keywords: "topcrash",
            keywords_type: "anywords",
            f1: "cf_status_firefox_beta",
            o1: "equals",
            v1: "affected",
            f2: "cf_status_firefox_release",
            o2: "anywordssubstr",
            v2: "unaffected, ---",
        },
        usesComponents: usesComponents,
    });

    BugList.append({
        id: "beta-perf-bug-affecting-beta",
        $container: $container,
        title: `${releases.beta.version} (Beta) Performance Bugs Affecting Beta`,
        description: "TODO",
        query: {
            resolution: "---",
            keywords: "regression, perf",
            keywords_type: "allwords",
            f1: "cf_status_firefox_beta",
            o1: "equals",
            v1: "affected",
            f2: "OP",
            j2: "OR",
            f3: "cf_status_firefox_release",
            o3: "equals",
            v3: "unaffected",
            f4: "cf_status_firefox_release",
            o4: "equals",
            v4: "?",
            f5: "cf_status_firefox_release",
            o5: "equals",
            v5: "---",
            f6: "CP",
            f7: "flagtypes.name",
            o7: "notsubstring",
            v7: "needinfo",
            f8: "cf_tracking_firefox_beta",
            o8: "notequals",
            v8: "-",
            f9: "product",
            o9: "notequals",
            v9: "Testing",
            f10: "keywords",
            o10: "notsubstring",
            v10: "stalled",
            f11: "product",
            o11: "notequals",
            v11: "Geckoview",
            f12: "resolution",
            o12: "nowordssubstr",
            v12: "DUPLICATE,WONTFIX,INVALID",
        },
        usesComponents: usesComponents,
    });

    BugList.append({
        id: "beta-sec-all-high-crit-affecting-beta",
        $container: $container,
        title: `${releases.beta.version} (Beta) Sec-High/Sec-All/Sec-Crit Affecting Beta`,
        description: "TODO",
        query: {
            keywords: "sec-high, sec-critical",
            keywords_type: "anywords",
            f1: "cf_status_firefox_beta",
            o1: "anywords",
            v1: "affected fix-optional",
            f2: "keywords",
            o2: "notsubstring",
            v2: "stalled",
        },
        usesComponents: usesComponents,
    });
}
